volumes:
    postgresql: null
    static: null
services:
    django:
        entrypoint: gunicorn --bind 0.0.0.0:8000 --capture-output --log-level info --log-file - cloudlinux.wsgi
        restart: unless-stopped
        build:
            context: backend
            dockerfile: Dockerfile
        environment:
            - DJANGO_SETTINGS_MODULE=cloudlinux.settings.dev
            - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
            - ALLOWED_HOSTS=${ALLOWED_HOSTS}
            - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
            - TZ=${TZ}
            - DB_NAME=${DB_NAME}
            - DB_HOST=pgbouncer
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
    db:
        image: postgres:15
        restart: unless-stopped
        volumes:
            - ./db/data:/var/lib/postgresql/data
            - ./db/conf:/etc/postgresql
            - ./db/log:/var/log/postgresql
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - TZ=${TZ}
    redis:
        image: redis:alpine3.12
        restart: unless-stopped
        ports:
            - "6379:6379"